/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package web.amazon.app.test.info;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
